name: TdvEdit
version: ${project.version}
main: de.militaermiltz.tdv.TdvEdit
api-version: 1.18
authors: [ Militalex ]
description: This plugin adds Commands to the game helping build tdv music.
depend:
  - ProtocolLib
  - NBTAPI

commands:
  modifyplaysound:
    description: Modifies playsound command arguments.
    usage: Right usage -> /modifyplaysound <from> <to> <argument filter (-sound, -volume, ...) > <new Value> <optional -> world>
    permission: tdvEdit.modifyPlaysound
    permission-message: You don't have the permission to do that.
  commandprepend:
    desciption: Prepends a String in cmd-Blocks.
    usage: Right usage -> /commandprepend <from> <to> <prepend String in ""> <optional -> cmd filter (playsound, particle, fill, ...) >
    permission: tdvEdit.commandPrepend
    permission-message: You don't have the permission to do that.
  crescendo:
    desciption: Generate in playsound commands a crescendo.
    usage: Right usage -> /crescendo <from x, y, z> <to x, z> <Direction> <min> <max>
    permission: tdvEdit.crescendo
    permission-message: You don't have the permission to do that.
  resourcepack:
    description: Shows Resourcepack Information.
    usage: /resourcepack
    permission: tdvEdit.resourcepack
    permission-message: You don't have the permission to do that.
  givenote:
    description: Gives player a musical block with specific note.
    usage: Right usage -> /givenote <note as letter or noteblocks click> <optional -> standard noteblock, when used -> noteblock (nb), commandblock (cb) or repeatingCommandblock (rcb)> <if cb/rcb -> choose instrument block> <optional if cb/rcb -> standard 1.0, when used -> volume as double>
    permission: tdvEdit.givenote
    permission-message: You don't have the permission to do that.
  modifycommandblockstates:
    description: Can modify commandblock BlockStates.
    usage: Right usage -> /modifycommandblockstates <from> <to> <change to BlockState -> [cb (normal commandblock) | rcb (repeating commandblock) | ccb (chain commandblock) | conditional | unconditional | needsRedstone | alwaysActive]>
    permission: tdvEdit.modifycommandblockstates
    permission-message: You don't have the permission to do that.
  showplaysoundstats:
    description: Shows playsound stats.
    usgae: Right usage -> /showplaysoundstats
    permission: tdvEdit.showplaysoundstats
    permission-message: You don't have the permission to do that.